### PR TITLE
Add build instructions and fix markdown

### PR DESCRIPTION
**Pull request by tomjn**
Fixes up the readme and adds formatting, build instructions, and documents dependencies for Mac OS

### CODE REVIEW

**Comment by ashdnazg** [comment]
This will force us to maintain documentation in two places...
There's a reason why documentation should be in the wiki

**Comment by ashdnazg** [comment]
You're very welcome to help us update https://springrts.com/wiki/Building_Spring_on_MacOSX

**Comment by tomjn** [comment]
Right now there is no build documentation of any kind for PR Downloader, but if there was, I'd move it to GitHub. That way if you have a copy of the code you also have all the documentation on how to build it, and you avoid the poor readability and a labyrinthine structure of the spring wiki.

Also, these aren't spring build instructions, these instructions are specific to PR Downloader

**Comment by ashdnazg** [comment]
PR downloader is mostly built by engine devs so obviously the build instructions are bundled together.
If you think it deserves separate build instructions, feel free to create that page in the wiki.
Even if it would be better to have all documentation on github, I hope you see that at the moment by putting the documentation here you're making the labyrinth more complex.

**Comment by gajop** [comment]
As this is a spring organization project, I think it makes more sense to put documentation on the wiki, alongside engine doc. A link is all you would need. This is much better for getting contributions than through Github.
PS: It's not a bad idea to have just the simplest doc (most general build and usage example) here, so people can understand how to use it at a glance

**Comment by ashdnazg** [comment]
@gajop I agree, it's exactly what we have in https://github.com/spring/spring

**Comment by tomjn** [comment]
I don't see how my PR is much different from the readme for https://github.com/spring/spring, it even links to the wiki for usage instructions. Eitherway I did what most developers will do and look at the readme, then look for a file labelled `install` or `instructions` and didn't find one. It wasn't obvious that the wiki would have the build instructions especially after clicking through and finding usage instructions.

The wiki only documents building spring itself on the assumption you want to build everything, and tbh the spring wiki is painful, even if the documentation was well written and well structured.

If someone wants to write super comprehensive build instructions and put them in the wiki, hooray, but in the meantime, can we have simple ones in the readme?

**Comment by ashdnazg** [comment]
@abma ?

**Comment by abma** [comment]
pr-downloader is shipped with spring, so usually there is no need to compile it separately.

-> build instructions should be in the wiki to have no duplicate docs

**Comment by tomjn** [comment]
@abma I'm happy to move all of it out of the wiki and into markdown docs that are fully searchable and indexed ( the entire thing, not just pr downloader ), as well as the wiki redirects.

You'd gain:

 - A much easier editing syntax
 - Free hosting on GitHub ( or gitbooks etc etc ) if you so choose
 - Every copy of spring source has an offline copy of the docs
 - There are tonnes of libraries and scripts to convert mediawiki content into Jekyll markdown, [e.g.](https://github.com/nicolasbock/mediawiki-jekyll)
 - You can convert to Mediawiki if you decide you want both and want to keep them in sync via [pandoc](http://pandoc.org/)
 - Jekyll themes that are easier to maintain than MediaWiki themes
 - The end result is static HTML, no DB!
 - Proper version control for the docs that people can use without needing to know git
 - The build process can easily be automated and tested via Travis in full

Just compare [this](https://springrts.com/wiki/Main_Page) with [this](https://docs.cloudcannon.com/building/versions/)

I'm away with work next week but when I'm back I can copy it all over and have something to demo if you'd like? Only if it's going to be seriously considered though. I'm not going to go over all the other wiki stuff like Lua docs or player guides atm

**Comment by abma** [comment]
no, i'm really against adding docs for pr-downloader to the git repository as pr-downloader is a submodule of spring:

https://github.com/spring/spring/tree/develop/tools

also pr-downloader is bundled with spring.

only thing which could be made is fix/add doxygen compatible comments to the sourcecode and then  generate documentation with doxygen.

if you have a specific problem: ask

**Comment by abma** [comment]
side note:

"brew cmake install minizip jsoncpp clang-format boost"

why is curl/libcurl missing there?

clang-format is optional.

the ci script is maybe most interesting:
https://github.com/spring/pr-downloader/blob/master/.travis.yml

**Comment by tomjn** [comment]
I wasn't referring specifically to PR Downloader, but to **everything**, starting with how to build spring itself, basically everything underneath engine development in the wiki. PR Downloader on its own would be fine with just a `readme.md`

**Comment by tomjn** [comment]
> why is curl/libcurl missing there?

Probably because it was already present on my system by default

**Comment by abma** [comment]
> I wasn't referring specifically to PR Downloader, but to everything, starting with how to build spring itself, basically everything underneath engine development in the wiki. PR Downloader on its own would be fine with just a readme.md

wrong bug tracker then, use https://springrts.com/mantis/

**Pull request closed without merging**
