### PR TITLE
add external hash calculation API (supporting only md5 atm)

### PR DESCRIPTION
**Pull request by gajop**
I know the +1 on line 255 and the string termination strings may look odd, but I've tested it and it works

### CODE REVIEW

**Comment by gajop** [comment]
Thanks

**Comment by abma** [comment]
thanks!

doesn't look odd. \0 needs space! ;)

for the curious, why not

    bool CalcHash(const char* str, int size, int type, char* res, int ressize);

?

this would make the caller alloc and free memory -> less error-prone

**Comment by gajop** [comment]
The caller shouldn't need to estimate size (especially annoying with multiple hash types), and I'm OK with contract programming (maybe it should be clearly spelled out that the string should be cleaned up after use?)
Would be much more satisfying to just use std::string though ;)

**Comment by abma** [comment]
ok, i see the conflict :)

i gave you push permissions, thx!

**Comment by gajop** [comment]
Neat, thanks

2015-11-22 1:31 GMT+09:00 abma <notifications@github.com>:

**Pull request merged**
